controller_list:
  - name: fake_left_arm_controller
    joints:
      - waist_lean
      - left_shoulder_side
      - left_shoulder_up
      - left_bicep_rotate
      - left_bicep
  - name: fake_right_arm_controller
    joints:
      - waist_lean
      - right_shoulder_side
      - right_shoulder_up
      - right_bicep_rotate
      - right_bicep