controller_list:
  - name: fake_base_controller
    joints:
      - virtual_joint
  - name: fake_right_arm_controller
    joints:
      - right_shoulder_side
      - right_shoulder_up
      - right_bicep_rotate
      - right_bicep
  - name: fake_left_arm_controller
    joints:
      - left_shoulder_side
      - left_shoulder_up
      - left_bicep_rotate
      - left_bicep